### ISSUE TITLE
 Cannot find module 'uniq'

### ISSUE THREAD

**Issue by Lucas-C** [hughsk/lock-versions#1]
```
λ npm install -g lock-versions
λ lock-versions package.json
module.js:327
    throw err;
    ^

Error: Cannot find module 'uniq'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\lock-versions\cli.js:5:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by artipixel** [comment]
+1

**Comment by SethFalco** [comment]
Just adding a note for anyone that encounters this project/issue in future.

Since [npm v5](https://github.com/npm/npm/releases/tag/v5.0.0) (May, 2017) the default behavior makes this package redundant. One can just commit their `package-lock.json`, `yarn.lock`, `pnpm-lock.yaml`, or whatever lockfile your packager manager of choice outputs.

This will not only lock direct dependencies, but also locks nested dependencies too. (i.e. dependencies of dependencies, which this wouldn't have done before lockfiles)
